Extension { #name : #UndefinedObject }

{ #category : #'*DeepTraverser-private' }
UndefinedObject >> action: anObject using: aStream [
]

{ #category : #'*DeepTraverser-private' }
UndefinedObject >> from: fromObject to: toObject using: aStream [
]

{ #category : #'*DeepTraverser-private' }
UndefinedObject >> traverse: anObject using: aStream [
	
]

{ #category : #'*DeepTraverser-private' }
UndefinedObject >> traverseUsing: aStream [
]
